apiVersion: intel.com/v1alpha1
kind: ClusterPolicy
metadata:
  name: gpu-policy
spec:
  resourceRegistration: dra
  useNFDLabeling: true
  resourceMonitoring: true
  kmm:
    useInTreeDriver: true
  dra:
    image: ghcr.io/intel/intel-resource-drivers-for-kubernetes/intel-gpu-resource-driver:v0.11.0
    podHealthCheck: true
  xpu:
    image: ghcr.io/intel/xpumanager/xpumd:v2.0.0
